import {
    FaHtml5,
    FaCss3,
    FaReact,
    FaNodeJs,
    FaPython,
    FaAws,
    FaGitAlt,
    FaLinux,
    FaLinkedin,
    FaInstagram,
    FaGithub,
} from "react-icons/fa"
import { IoLogoJavascript } from "react-icons/io";
import { 
    SiTailwindcss,
    SiNextdotjs,
    SiExpress,
    SiJquery,
    SiMysql,
    SiPostgresql,
    SiAssemblyscript,
    SiWireshark,
 } from "react-icons/si";
 import { TbBrandCpp, TbBrandVscode } from "react-icons/tb";
 import { MdOutlineSecurity, MdCrisisAlert, MdEmail } from "react-icons/md";
 import { ImBlog } from "react-icons/im";
 import frontend from "/frontend.png"
 import backend from "/backend.png"
 import tools from "/tools.png"
 import cyber from "/cyber.png"
 import blogs from "/blogs.jpg"
 import cocktail from "/cocktail.jpg"
 import p1 from "/p1.jpg"
 import p2 from "/p2.jpg"
 import p3 from "/p3.jpg"
 import p4 from "/p4.jpg"

export const SKILLS = [
    {
        title: "Frontend",
        icon: frontend,
        skills: [
            { skill: "HTML5", Img: FaHtml5, percent: "70%" },
            { skill: "CSS3", Img: FaCss3, percent: "80%" },
            { skill: "JavaScript", Img: IoLogoJavascript, percent: "85%" },
            { skill: "React.js", Img: FaReact, percent: "80%" },
            { skill: "Tailwind", Img: SiTailwindcss, percent: "70%" },
        ],
    },
        {
        title: "Backend",
        icon: backend,
        skills: [
            { skill: "Next.js", Img: SiNextdotjs, percent: "60%"  },
            { skill: "Node.js", Img: FaNodeJs, percent: "65%"  },
            { skill: "Express.js", Img: SiExpress, percent: "65%"  },
            { skill: "jQuery", Img: SiJquery, percent: "70%"  },
            { skill: "MySQL", Img: SiMysql, percent: "90%"  },
            { skill: "PostGreSQL", Img: SiPostgresql, percent: "85%"  },
        ],
    },
        {
        title: "Tools",
        icon: tools,
        skills: [
            { skill: "C++", Img: TbBrandCpp, percent: "90%" },
            { skill: "Python", Img: FaPython, percent: "85%" },
            { skill: "Assembly", Img: SiAssemblyscript, percent: "70%" },
            { skill: "AWS", Img: FaAws, percent: "70%" },
            { skill: "Git/Github", Img: FaGitAlt, percent: "90%" },
            { skill: "VS Code", Img: TbBrandVscode, percent: "90%" },
            { skill: "Linux", Img: FaLinux, percent: "80%" },
        ],
    },
        {
        title: "Security",
        icon: cyber,
        skills: [
            { skill: "SIEM", Img: MdOutlineSecurity, percent: "70%" },
            { skill: "IDS", Img: MdCrisisAlert, percent: "70%" },
            { skill: "Packet", Img: SiWireshark, percent: "80%" },
        ],
    },
];

export const SOCIALS = [
  {
    id: "0",
    title: "Likedin",
    img: FaLinkedin,
    url: "https://www.linkedin.com/in/junseok-oh/",
  },
  {
    id: "1",
    title: "Instagram",
    img: FaInstagram,
    url: "https://www.instagram.com/junseok0h/",
  },
  {
    id: "2",
    title: "Github",
    img: FaGithub,
    url: "https://github.com/eDi9root",
  },
  {
    id: "3",
    title: "Blogs",
    img: ImBlog,
    url: "#",
  },
];


export const PROJECTS = [
    {
        title: "SOC Automation",
        front: "Implemented a Security Operations Center (SOC) automation workflow",
        content: "Implemented a Security Operations Center (SOC) automation workflow using Wazuh, Shuffle, and The Hive to enhance threat detection, incident response, and case management capabilities. |  Integrated The Hive for advanced case management, automating the creation and enrichment of incident reports from alerts generated by Wazuh and Shuffle, improving incident tracking and analysis.",
        url: "https://edi9root-blog.vercel.app/tags/SOC",
        img: p3
    },
    {
        title: "Blogs",
        front: "Designed personal blogs, you can visit and enjoy.",
        content: "Built with Javascript, Next.js, NPM, Supabase, TailwindCss",
        url: "https://github.com/eDi9root/blog-next",
        img: blogs
    },
    {
        title: "Blue Team Home Lab  Cybersecurity",
        front: "Designed and implemented a comprehensive cybersecurity home lab to enhance practical skills and knowledge",
        content: "Designed and implemented a comprehensive cybersecurity home lab to enhance practical skills and knowledge in network security, threat detection, incident response and penetration testing. | Maintained a segmented network architecture with different subnets to ensure isolated and controlled environments for different activities. | Configured a firewall for network security, including setting up rules and monitoring traffic to safeguard against unauthorized access and threats.",
        url: "https://edi9root-blog.vercel.app/tags/cybersecurity",
        img: p3
    },
    {
        title: "ANTQUANT",
        front: "Designed and built the development environment by applying the securities firm APIs.",
        content: "Designed and built the development environment by applying the securities firm APIs. Based on the concept of quantitative investing, I created my own strategy and applied it by extracted data through web crawling and APIs, and managed it using an AWS database.",
        url: "https://github.com/eDi9root/SystemTrading",
        img: p1
    },
    {
        title: "FTZ_Writeup",
        front: "Built my own environments and analyze the principles of system hacking step by step based on hackerschool ftz",
        content: "Using hackerschool ftz, I analyze the principles of system hacking step by step. At each stage, I identify and analyze problems, then execute attacks. I explore various methods and principles such as memory manipulation, backdoors, buffer overflows, and conduct analysis through reverse engineering.",
        url: "https://github.com/eDi9root/FTZ-Writeup",
        img: p2
    },
    {
        title: "Chess_game",
        front: "Designed a chess engine using C++ programming language and algorithms",
        content: "Designed a chess engine using c++ programming language and algorithms. Also, adopted some design patterns such as observer, decorator, factory, and template. Chess v2.0 is currently being built.",
        url: "https://github.com/eDi9root/CS246_CHESS",
        img: p4
    },
]
